### ISSUE TITLE
update readme.md as it's supporting yarn install and yarn start

### ISSUE THREAD

**Issue by nil4you** [KaiHotz/React-Redux-Simple-Starter#3]

**Comment by KaiHotz** [comment]
@nil4you Yes you are right, this project like any other project that is bootstrapped  wit create-creact-app supports yarn, but therefor you would need to delete the package-lock.json since yarn creates its own yarn.lock file and having both on one project causes conflicts. Also i don't recommend to delete the package-lock.json file, if you do so you wont get the locked version of dependencies that i recommend to use on this project. This is why the documentation only states npm for installation.  Any experienced developer of course might do the change to yarn on its own
